package:
  name: plotsr
  version: {{ version }}

source:
  path: ../

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vvv"

requirements:
  host:
    - python
    - pip
  run:
    - python
    - numpy   >=1.21
    - matplotlib-base  >=3.3
    - pandas  >=1.2.4

test:
  commands:
    - plotsr --version

about:
  home: https://github.com/schneebergerlab/plotsr
  license: MIT License
  license_file: LICENSE
  summary: PVisualiser for structural annotations between multiple genomes

extra:
  maintainers:
    - Manish Goel <goel@mpipz.mpg.de>

